FinalTUFOD/FinalTUFOD/Models/Classes/AdminPage.cs
using System.ComponentModel.DataAnnotations;

namespace FinalTUFOD.Models.Classes
{
    public class AdminPage
    {
        [Key]
        public int id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
    }
}

FinalTUFOD/FinalTUFOD/Models/Classes/Context.cs
using System.Data.Entity;

namespace FinalTUFOD.Models.Classes
{
    public class Context : DbContext
    {
        public DbSet<AdminPage> Admins { get; set; }
        public DbSet<HomePage> HomePages { get; set; }
        public DbSet<Icons> icons { get; set; }
    }
}

FinalTUFOD/FinalTUFOD/Models/Classes/HomePage.cs
using System.ComponentModel.DataAnnotations;

namespace FinalTUFOD.Models.Classes
{
    public class HomePage
    {
        [Key]
        public int id { get; set; }
        public string profile { get; set; }
        public string name { get; set; }
        public string content { get; set; }
        public string contant { get; set; }
        public string newshead { get; set; }
        public string news1head { get; set; }
        public string news1 { get; set; }
        public string news2head { get; set; }
        public string news2 { get; set; }
        public string news3head { get; set; }
        public string news3 { get; set; }
        public string news4head { get; set; }
        public string news4 { get; set; }
    }
}

FinalTUFOD/FinalTUFOD/Models/Classes/Icons.cs
using System.ComponentModel.DataAnnotations;

namespace FinalTUFOD.Models.Classes
{
    public class Icons
    {
        [Key]
        public int id { get; set; }
        public string icon { get; set; }
        public string link { get; set; }
    }
}

FinalTUFOD/FinalTUFOD/Controllers/AdminController.cs
using FinalTUFOD.Models.Classes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FinalTUFOD.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        Context c = new Context();
        [Authorize]
        public ActionResult Index() // admin paneli anasayfası
        {
            var variable = c.HomePages.ToList(); // listeleme işlemi veritabanı için
            return View(variable);
        }
        public ActionResult GoToHomePage(int id) // güncelleme işlemleri için verinin bulunmasını sağlayacak fonksiyon
        { // id'ye göre arama yapar
            var gth = c.HomePages.Find(id);
            return View("GoToHomePage", gth);
        }
        public ActionResult UpdateHomePage(HomePage x)
        {
            var hp = c.HomePages.Find(x.id);
            hp.name = x.name; // veritabanındaki nesne ile eklediğim nesneyi değiştirir/üzerine yazar.
            hp.content = x.content;
            hp.newshead = x.newshead;
            hp.contant = x.contant;
            hp.news1head = x.news1head;
            hp.news2head = x.news2head;
            hp.news3head = x.news3head;
            hp.news4head = x.news4head;
            hp.news1 = x.news1;
            hp.news2 = x.news2;
            hp.news3 = x.news3;
            hp.news4 = x.news4;
            c.SaveChanges(); // kaydeder
            return RedirectToAction("Index"); // anasayfaya yönlendirir
        }
        public ActionResult iconList() // ikonları listelememizi sağlayan fonksiyon
        {
            var variable = c.icons.ToList();
            return View(variable);
        }
        [HttpGet]
        public ActionResult newIcon()
        {
            return View();
        }
        [HttpPost]
        public ActionResult newIcon(Icons p)
        {
            c.icons.Add(p); // yeni ikon ekleyip kaydedip ikon anasayfasına gönderen komutlar
            c.SaveChanges();
            return RedirectToAction("iconList");
        }
        public ActionResult GoToIcon(int id) // güncelleme işlemleri için verinin bulunmasını sağlayacak fonksiyon
        { // id'ye göre arama yapar
            var gti = c.icons.Find(id);
            return View("GoToIcon", gti);
        }
        public ActionResult UpdateIcon(Icons x)
        { // id'ye göre bulunan ikonun üzerine yeni ikon ve linkini ekleyip kaydedip ikon anasayfasına yönlendiren komutlar
            var ic = c.icons.Find(x.id);
            ic.icon = x.icon;
            ic.link = x.link;
            c.SaveChanges();
            return RedirectToAction("iconList");
        }
        public ActionResult DeleteIcon(int id)
        {
            var di = c.icons.Find(id); // id'ye göre buluyor
            c.icons.Remove(di); // siliyor
            c.SaveChanges(); // kaydediyor
            return RedirectToAction("iconList"); // ikon sayfasına yönlendiriyor
        }
    }
}

FinalTUFOD/FinalTUFOD/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FinalTUFOD.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

FinalTUFOD/FinalTUFOD/Controllers/HomePageController.cs
using FinalTUFOD.Models.Classes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FinalTUFOD.Controllers
{
    public class HomePageController : Controller
    {
        // GET: HomePage
        Context c = new Context();
        public ActionResult Index() // anasayfa
        {
            var variable = c.HomePages.ToList(); // listeleme işlemi veritabanı için
            return View(variable);
        }

        public PartialViewResult icons() // iconların kayıt tutulduğu view
        {
            var variable = c.icons.ToList(); // listeleme işlemi veritabanı için
            return PartialView(variable);
        }
    }
}

FinalTUFOD/FinalTUFOD/Controllers/LoginController.cs
using FinalTUFOD.Models.Classes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace FinalTUFOD.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        Context c = new Context();
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(AdminPage ad)
        { // şifre ve kullanıcı adı doğru ise admin paneline yönlendiren fonksiyon
            var info = c.Admins.FirstOrDefault(x => x.username == ad.username && x.password == ad.password);
            if(info != null)
            {
                FormsAuthentication.SetAuthCookie(info.username, false); 
                Session["username"] = info.username.ToString();
                return RedirectToAction("Index", "Admin"); // doğru girilince admin paneline yönlendirilir
            } // yanlışsa login panelindee kalmaya devam eder
            else
            {
                return View();
            }
        }
        public ActionResult LogOut()
        { // çıkış yapma işlemi
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Login"); // login paneline yönlendirir.
        }
    }
}

FinalTUFOD/FinalTUFOD/Views/Admin/GoToHomePage.cshtml
@model FinalTUFOD.Models.Classes.HomePage
@{
    ViewBag.Title = "UpdateHomePage";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<!-- anasayfadaki verileri güncelleme ekranı -->
<h2 class="mt-4">Update Home Page</h2> 
<hr />
@using (Html.BeginForm("UpdateHomePage", "Admin", FormMethod.Post))
{
    @Html.LabelFor(x => x.id) // id değiştirilemez sadece okunabilir
    @Html.TextBoxFor(x => x.id, new { @class = "form-control", @readonly = "readonly" })
    <br />
    @Html.LabelFor(x => x.name)
    @Html.TextBoxFor(x => x.name, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.content)
    @Html.TextBoxFor(x => x.content, new { @class = "form-control"})
    <br />
    @Html.LabelFor(x => x.newshead)
    @Html.TextBoxFor(x => x.newshead, new { @class = "form-control"})
    <br />
    @Html.LabelFor(x => x.contant)
    @Html.TextBoxFor(x => x.contant, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.news1head)
    @Html.TextBoxFor(x => x.news1head, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.news2head)
    @Html.TextBoxFor(x => x.news2head, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.news3head)
    @Html.TextBoxFor(x => x.news3head, new { @class = "form-control"})
    <br />
    @Html.LabelFor(x => x.news4head)
    @Html.TextBoxFor(x => x.news4head, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.news1)
    @Html.TextBoxFor(x => x.news1, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.news2)
    @Html.TextBoxFor(x => x.news2, new { @class = "form-control"})
    <br />
    @Html.LabelFor(x => x.news3)
    @Html.TextBoxFor(x => x.news3, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.news4)
    @Html.TextBoxFor(x => x.news4, new { @class = "form-control" })
    <br />
    <button class="btn btn-success">UPDATE</button>
}

FinalTUFOD/FinalTUFOD/Views/Admin/GoToIcon.cshtml
@model FinalTUFOD.Models.Classes.Icons
@{
    ViewBag.Title = "GoToIcon";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<!-- ikon anasayfasındaki verileri güncelleme ekranı -->
<h2>Update Icon</h2>
<br />
@using (Html.BeginForm("UpdateIcon", "Admin", FormMethod.Post))
{
    @Html.LabelFor(x => x.id) // id değiştirilemez sadece okunabilir
    @Html.TextBoxFor(x => x.id, new { @class = "form-control", @readonly = "readonly" })
    <br />
    @Html.LabelFor(x => x.icon)
    @Html.TextBoxFor(x => x.icon, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.link)
    @Html.TextBoxFor(x => x.link, new { @class = "form-control" })
    <br />
    <button class="btn btn-success">UPDATE</button>
}

FinalTUFOD/FinalTUFOD/Views/Admin/Index.cshtml
@using FinalTUFOD.Models.Classes
@model List<HomePage>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<h4 class="mb-4">HOME PAGE</h4>
<table class="table table-bordered mt-3">
    <tr>
        <th>ID</th>
        <th>NAME</th>
        <th>UPDATE</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.id</td>
            <td>@x.name</td>
            <td><a href="/Admin/GoToHomePage/@x.id" class="btn btn-primary">UPDATE</a></td>
        </tr>
    }

</table>

FinalTUFOD/FinalTUFOD/Views/Admin/iconList.cshtml
@using FinalTUFOD.Models.Classes
@model List<Icons>
@{
    ViewBag.Title = "iconList";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<h4 class="mb-4">ICON PAGE</h4>
<table class="table table-bordered">
    <tr>
        <!--ikon anasayfası tablosu-->
        <th>ID</th>
        <th>ICON</th>
        <th>UPDATE</th>
        <th>DELETE</th>
    </tr>
    @foreach (var x in Model)
    {<!--ikon anasayfası veritabanı bağlantısı-->
        <tr>
            <td>@x.id</td>
            <td><i class="@x.icon"></i></td>
            <td><a href="/Admin/GoToIcon/@x.id" class="btn btn-primary">UPDATE</a></td>
            <td><a href="/Admin/DeleteIcon/@x.id" class="btn btn-danger">DELETE</a></td>
        </tr>
    }
</table>
<a href="/Admin/newIcon/" class="btn btn-primary">ADD NEW ICON</a>

FinalTUFOD/FinalTUFOD/Views/Admin/newIcon.cshtml
@model FinalTUFOD.Models.Classes.Icons
@{
    ViewBag.Title = "newIcon";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<!--yeni ikonu veritabanına da eklememizi sağlayan bağlantı-->
<h2>ADD NEW ICON</h2><br />
<form class="form-group" method="post">
    @Html.LabelFor(x => x.icon)
    @Html.TextBoxFor(x => x.icon, new {@class = "form-control"})
    <br />
    @Html.LabelFor(x => x.link)
    @Html.TextBoxFor(x => x.link, new {@class = "form-control"})
    <br />
    <button class="btn btn-primary">ADD ICON</button>
</form> 

FinalTUFOD/FinalTUFOD/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

FinalTUFOD/FinalTUFOD/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

FinalTUFOD/FinalTUFOD/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

FinalTUFOD/FinalTUFOD/Views/HomePage/Index.cshtml
@using FinalTUFOD.Models.Classes
@model List<HomePage>

@{
    Layout = null;
}
<!--anasayfadaki verilerin veritabanından çekilmesini sağlayan bağlantıların olduğu sayfa-->
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="utf-8">
    <meta name="veiwport" content="width=device-width, initial-scale=1.0">
    <title>TUFOD</title>
    <link rel="stylesheet" type="text/css" href="~/Web-Tufod-Index/style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
</head>
<body>
    <div class="adminLogin"> <!--admin sayfasına yönlendiren alan-->
        <a href="/Admin/Index"><i class="fas fa-user"></i></a>
    </div>
    <div class="center">
        <div class="aboutHim">
            @foreach (var x in Model)
            {
                <h1><b><u>@x.name</u></b></h1>
                <p>@x.content</p><br />
                <h1><u>@x.newshead</u></h1>
                <div class="newsContent">
                    <input type="checkbox" class="read-more-state" id="post-1" />
                    <div class="read-more-wrap"> <p>@x.news1head <span class="read-more-target"> @x.news1</span></p></div>
                    <label for="post-1" class="read-more-trigger"></label>
                </div>
                <div class="newsContent">
                    <input type="checkbox" class="read-more-state" id="post-2" />
                    <div class="read-more-wrap"><p>@x.news2head <span class="read-more-target">  @x.news2</span></p></div>
                    <label for="post-2" class="read-more-trigger"></label>
                </div>
                <div class="newsContent">
                    <input type="checkbox" class="read-more-state" id="post-3" />
                    <div class="read-more-wrap"><p>@x.news3head  <span class="read-more-target"> @x.news3</span></p></div>
                    <label for="post-3" class="read-more-trigger"></label>
                </div>
                <div class="newsContent">
                    <input type="checkbox" class="read-more-state" id="post-4" />
                    <div class="read-more-wrap"><p>@x.news4head <span class="read-more-target"> @x.news4</span></p></div>
                    <label for="post-4" class="read-more-trigger"></label>
                </div><br />
                <h4>@x.contant</h4>
            }
        </div>
        @Html.Action("icons", "HomePage")
    </div>
</body>
</html>

FinalTUFOD/FinalTUFOD/Views/HomePage/icons.cshtml
@using FinalTUFOD.Models.Classes
@model List<Icons>

<div class="social">
    @foreach (var x in Model)
    {
        <a href="@x.link"><i class="@x.icon"></i></a>
    }
    <!--anasayfadaki ikonların da veritabanından çekilerek görüntülenmesini sağlayan bağlantı-->
</div>

FinalTUFOD/FinalTUFOD/Views/Login/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TUFOD ADMIN PANELİ</title>
    <link rel="stylesheet" href="~/Web-Admin-Login/css/style.css">
</head>
<body>
    <div class="container">
        <div class="contact-form">
            <a href="/HomePage/Index/"><img src="~/Web-Admin-Login/img/photo.png" class="admin-img"></a> <!--anasayfaya yönlendiren alan-->
            <h2><u>Admin Login</u></h2>
            @using (Html.BeginForm("Index", "Login", FormMethod.Post))
            { <!--kullanıcı giriş alanı-->
                <div class="txtb">
                    <input type="text" name="username" placeholder="Username">
                </div>
                <div class="txtb">
                    <input type="password" name="password" placeholder="Password">
                </div>
                <input type="submit" class="logbtn" value="Log In">
            }
        </div>
    </div>
</body>
</html>

FinalTUFOD/FinalTUFOD/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <title>TUFOD ADMİN PANELİ</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
</head>

<body>
    <div class="w3-sidebar w3-bar-block w3-card w3-animate-left" style="display:none;" id="mySidebar">
        <button class="w3-bar-item w3-button w3-large"
                onclick="w3_close()">
            Close &times;
        </button> <!--sidebar-->
        <a href="/Admin/Index" class="w3-bar-item w3-button">HOME PAGE</a>
        <a href="/Admin/iconList" class="w3-bar-item w3-button">ICONS</a>
        <a href="/HomePage/Index" target="_blank" class="w3-bar-item w3-button btn-outline-primary">TUFOD HOME PAGE</a>
        <a href="/Login/LogOut/" class="w3-bar-item w3-button btn-outline-danger">SIGN OUT</a>
    </div>

    <div id="main">
        <div class="w3-teal">
            <button id="openNav" class="w3-button w3-teal w3-xlarge" onclick="w3_open()">&#9776;</button>
            <div class="w3-container">
                <h1>TUFOD</h1>
            </div>
        </div>

        <div class="w3-container">
           @RenderBody() <!--sidebarın sabit kalmasını sağlayan bağlantı-->
        </div>

    </div>

    <script>
        function w3_open() {
            document.getElementById("main").style.marginLeft = "25%";
            document.getElementById("mySidebar").style.width = "25%";
          document.getElementById("mySidebar").style.display = "block";
          document.getElementById("openNav").style.display = 'none';
        }
        function w3_close() {
          document.getElementById("main").style.marginLeft = "0%";
            document.getElementById("mySidebar").style.display = "none";
            document.getElementById("openNav").style.display = "inline-block";
        }
    </script>

</body>
</html>

FinalTUFOD/FinalTUFOD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>